### ISSUE TITLE
SQE - Netbeans 7.4

### ISSUE THREAD

**Issue by kjguruprasad** [sqe-team/sqe#11]
I am unable to install SQE in Netbeans 7.4 with JDK 1.7.  Please Guide

**Comment by fvogler** [comment]
Hi,
at the moment, there are no plans to support 7.4.
The current Netbeans version is 8.1.
I've already switched the codebase to Java8.

Is there no way to upgrade?
What is your environment?

Regards
Florian

**Comment by fvogler** [comment]
Hi,
I close this issue. If there is really a large need, please let me know.
