### ISSUE TITLE
checkstyle use "StrictDuplicateCode" may cause erro

### ISSUE THREAD

**Issue by luosoy** [sqe-team/sqe#12]
netbeans version is 8.1

the checkstyle.xml:
   <module name="StrictDuplicateCode">
        <property name="min" value="15"/>
    </module>

Please also recheck that provided ClassLoader to Checker is configured correctly.
    at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:168)
    at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:137)
[catch] at org.nbheaven.sqe.tools.checkstyle.codedefects.core.internal.CheckstyleScannerJob.init(CheckstyleScannerJob.java:132)
    at org.nbheaven.sqe.tools.checkstyle.codedefects.core.internal.CheckstyleScannerJob.scan(CheckstyleScannerJob.java:151)
    at org.nbheaven.sqe.codedefects.core.spi.SQECodedefectScanner$Job.run(SQECodedefectScanner.java:54)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
    at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

**Comment by fvogler** [comment]
Hi,
thanks for your feedback. Can you provide more information?
What kind of project to you use? Can you provide an example project?

Regards
Florian

**Comment by luosoy** [comment]
Hi,
if the checkstyle.xml have  module name="StrictDuplicateCode"  and then property name="min" value="15"，i run checkstyle the erro will display

com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'StrictDuplicateCodeCheck' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.blocks.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.coding.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.design.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.header.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.imports.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.indentation.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.javadoc.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.metrics.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.modifier.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.naming.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.regexp.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.sizes.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.whitespace.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.checks.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.filters.StrictDuplicateCodeCheck, com.puppycrawl.tools.checkstyle.StrictDuplicateCodeCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
    at com.puppycrawl.tools.checkstyle.PackageObjectFactory.doMakeObject(PackageObjectFactory.java:115)
    at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:156)
Caused: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to instantiate 'StrictDuplicateCode' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.blocks.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.coding.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.design.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.header.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.imports.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.indentation.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.javadoc.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.metrics.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.modifier.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.naming.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.regexp.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.sizes.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.whitespace.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.filters.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.StrictDuplicateCode. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
    at com.puppycrawl.tools.checkstyle.PackageObjectFactory.createModule(PackageObjectFactory.java:163)
    at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:158)
Caused: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module StrictDuplicateCode - Unable to instantiate 'StrictDuplicateCode' class, it is also not possible to instantiate it as com.puppycrawl.tools.checkstyle.checks.annotation.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.blocks.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.coding.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.design.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.header.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.imports.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.indentation.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.javadoc.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.metrics.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.modifier.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.naming.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.regexp.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.sizes.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.whitespace.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.checks.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.filters.StrictDuplicateCode, com.puppycrawl.tools.checkstyle.StrictDuplicateCode. Please recheck that class name is specified as canonical name or read how to configure short name usage http://checkstyle.sourceforge.net/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.
    at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:168)
    at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:137)
[catch] at org.nbheaven.sqe.tools.checkstyle.codedefects.core.internal.CheckstyleScannerJob.init(CheckstyleScannerJob.java:132)
    at org.nbheaven.sqe.tools.checkstyle.codedefects.core.internal.CheckstyleScannerJob.scan(CheckstyleScannerJob.java:151)
    at org.nbheaven.sqe.codedefects.core.spi.SQECodedefectScanner$Job.run(SQECodedefectScanner.java:54)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
    at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

**Comment by fvogler** [comment]
Hi,
this check is not supported any more, as far as I see.
Can't find him in the current check list. http://checkstyle.sourceforge.net/checks.html

I will close the issue if it is ok for you.

Regards
Florian

_See Checkstyle Release Note:_
(https://github.com/checkstyle/checkstyle/blob/master/src/xdocs/releasenotes.xml)

Release 6.2
    Breaking backward compatibility:
        Remove StrictDuplicateCodeCheck and whole package. Author: Michal Kordas #523

**Comment by luosoy** [comment]
thanks for you.
